function [dot_x_num,J_x_num,h_num,J_h_num] = vehicle_dynamics_numeric(in1,Fx,Mz)
%VEHICLE_DYNAMICS_NUMERIC
%    [DOT_X_NUM,J_x_num,H_NUM,J_h_num] = VEHICLE_DYNAMICS_NUMERIC(IN1,Fx,Mz)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    09-Jul-2026 16:44:50

phi = in1(1,:);
phi_u = in1(6,:);
vx = in1(5,:);
vy = in1(3,:);
wx = in1(2,:);
wz = in1(4,:);
t2 = ((vx < 1.0./1.0e+1) & (0.0 <= vx));
t3 = ((-1.0./1.0e+1 < vx) & (vx < 1.0./1.0e+1));
t4 = cos(phi);
t5 = sin(phi);
t6 = vx.*wz;
t7 = wz.*2.0;
t8 = -vx;
t9 = 1.0./vx;
t11 = -wz;
t14 = wz.*(7.0./4.0);
t17 = vy.*3.0e+5;
t18 = wz.*(7.3e+1./2.0e+1);
t19 = wz.*5.235e+5;
t20 = wz.*(3.39e+2./1.0e+2);
t21 = wz.*5.395e+1;
t33 = wz.*3.779475965327029e+1;
t34 = wz.*6.088427895981087e+5;
t53 = Mz.*2.832172067707477e-5;
t56 = vy.*4.57962223348299e+1;
t61 = wz.*1.31628878670393e+2;
t62 = vy.*4.684147109188938e+1;
t63 = wz.*1.262377645926419e+2;
t64 = phi.*1.808379730678007e+2;
t65 = phi_u.*1.808379730678007e+2;
t66 = wx.*4.520949326695016e+1;
t76 = vy.*2.059906868759754e+2;
t78 = wz.*5.551449011307536e+2;
t133 = vx.*4.397613526523994;
t134 = wz.*4.397613526523994;
t10 = t9.^2;
t12 = -t7;
t13 = -t6;
t16 = t14+vy;
t22 = -t19;
t23 = cos(t21);
t24 = sin(t21);
t25 = t18+vy;
t26 = -t20;
t28 = t9.*wz.*1.6185e+5;
t30 = t9.*wz.*5.395;
t35 = cos(t33);
t36 = sin(t33);
t37 = -t34;
t41 = t9.*wz.*1.133842789598109e+5;
t45 = t9.*wz.*3.779475965327029;
t54 = t4.*2.840464562345316e+1;
t55 = t5.*2.840464562345316e+1;
t69 = -t62;
t70 = -t63;
t71 = -t64;
t72 = -t66;
t73 = t9.*4.684147109188938;
t74 = t9.*1.262377645926419e+1;
t77 = -t76;
t79 = t9.*2.059906868759754e+1;
t80 = -t78;
t89 = t9.*5.551449011307536e+1;
t136 = -t133;
t137 = -t134;
t15 = t12+vy;
t27 = t26+vy;
t29 = t10.*wz.*1.6185e+5;
t31 = cos(t30);
t32 = sin(t30);
t40 = t17+t22;
t42 = t10.*wz.*1.133842789598109e+5;
t48 = cos(t45);
t49 = sin(t45);
t52 = t17+t37;
t57 = -t54;
t58 = -t55;
t75 = -t73;
t83 = -t79;
t85 = t23.*3.101228414139687e+1;
t86 = t23.*5.411643582673754e+1;
t87 = t23.*2.342073554594469e+1;
t88 = t23.*4.086918352767349e+1;
t96 = t23.*1.029953434379877e+2;
t99 = t35.*1.486890335546425e+1;
t101 = t23.*1.797268742992885e+2;
t102 = t35.*2.342073554594469e+1;
t110 = t35.*1.029953434379877e+2;
t112 = t35.*4.753181988077517e+1;
t113 = t35.*3.017608199068512e+1;
t122 = t35.*2.09026574047999e+2;
t90 = -t88;
t91 = -t87;
t100 = -t96;
t103 = -t101;
t104 = t9.*t31.*2.342073554594469;
t105 = -t102;
t107 = t9.*t31.*4.086918352767349;
t114 = -t110;
t115 = t23.*t40.*7.80691184864823e-5;
t116 = -t112;
t117 = t9.*t31.*1.029953434379877e+1;
t120 = t9.*t48.*2.342073554594469;
t121 = t9.*t31.*1.797268742992885e+1;
t124 = t23.*t40.*1.033742804713229e-4;
t125 = -t122;
t126 = t24.*t40.*5.577042431427871e-3;
t127 = t24.*t40.*4.21182894234572e-3;
t129 = t9.*t48.*1.029953434379877e+1;
t131 = t9.*t48.*4.753181988077517;
t132 = t23.*t40.*3.43317811459959e-4;
t140 = t24.*t40.*1.852199592826479e-2;
t141 = t9.*t48.*2.09026574047999e+1;
t142 = t35.*t52.*7.80691184864823e-5;
t144 = t35.*t52.*4.956301118488085e-5;
t145 = t57-1.808379730678007e+2;
t147 = t36.*t52.*1.873222095424919e-3;
t150 = t35.*t52.*3.43317811459959e-4;
t151 = t36.*t52.*2.950603569539279e-3;
t157 = t36.*t52.*1.297561416881591e-2;
t178 = t87+t102+4.684147109188938e+1;
t180 = t96+t110+2.059906868759754e+2;
t106 = -t104;
t118 = -t115;
t119 = -t117;
t123 = -t120;
t128 = -t127;
t130 = -t129;
t135 = -t132;
t143 = -t140;
t146 = -t142;
t153 = -t150;
t154 = -t151;
t161 = -t157;
t179 = t91+t105-4.684147109188938e+1;
t181 = t100+t114-2.059906868759754e+2;
t184 = t13+t62+t70+t115+t142;
t187 = t8+t88+t112+t127+t151+1.262377645926419e+2;
t190 = t101+t122+t136+t140+t157+5.551449011307536e+2;
t182 = t75+t106+t123;
t183 = t83+t119+t130;
t185 = t13+t63+t69+t118+t146;
et1 = t71+t65+t58+t72+(-4.397613526523994).*t6+t31.*(t28-t9.*(t25).*3.0e+4).*3.43317811459959e-4+t48.*(t41-t9.*(t16).*3.0e+4).*3.43317811459959e-4;
et2 = t9.*(t15).*(-1.029953434379877e+1)-t9.*(t27).*1.029953434379877e+1;
if ~all(cellfun(@isscalar,{t2,t3}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (t2)
    t0 = t6.*(-4.397613526523994)+t58+t65+t71+t72+t77+t78+t135+t153;
elseif (t3)
    t0 = t6.*(-4.397613526523994)+t58+t65+t71+t72+t76+t80+t132+t150;
else
    t0 = et1+et2;
end
mt1 = [wx;t0];
if ~all(cellfun(@isscalar,{t2,t3}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (t2)
    t0 = t185;
elseif (t3)
    t0 = t184;
else
    t0 = t13-t9.*t15.*2.342073554594469-t9.*t27.*2.342073554594469+t31.*(t28-t9.*t25.*3.0e+4).*7.80691184864823e-5+t48.*(t41-t9.*t16.*3.0e+4).*7.80691184864823e-5;
end
mt2 = [t0];
if ~all(cellfun(@isscalar,{t2,t3}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (t2)
    t0 = t53+t56-t61-t124-t144;
elseif (t3)
    t0 = t53-t56+t61+t124+t144;
else
    t0 = t53+t9.*t15.*1.699303240624486+t9.*t27.*2.880318992858504+t31.*(t28-t9.*t25.*3.0e+4).*1.033742804713229e-4+t48.*(t41-t9.*t16.*3.0e+4).*4.956301118488085e-5;
end
mt3 = [t0];
mt4 = [Fx.*7.80691184864823e-5+vy.*wz;0.0];
dot_x_num = [mt1;mt2;mt3;mt4];
if nargout > 1
    t188 = t8+t90+t116+t128+t154-1.262377645926419e+2;
    t191 = t103+t125+t136+t143+t161-5.551449011307536e+2;
    if ~all(cellfun(@isscalar,{t2,t3}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (t2)    t192 = t179;elseif (t3)    t192 = t178;else    t192 = t182;end;
    if ~all(cellfun(@isscalar,{t2,t3}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (t2)    t198 = t181;elseif (t3)    t198 = t180;else    t198 = t183;end;
    et3 = t137-t31.*(t29-t10.*(t25).*3.0e+4).*3.43317811459959e-4-t48.*(t42-t10.*(t16).*3.0e+4).*3.43317811459959e-4+t10.*(t15).*1.029953434379877e+1+t10.*(t27).*1.029953434379877e+1;
    et4 = t10.*t32.*wz.*(t28-t9.*(t25).*3.0e+4).*1.852199592826479e-3+t10.*t49.*wz.*(t41-t9.*(t16).*3.0e+4).*1.297561416881591e-3;
    et5 = t11-t31.*(t29-t10.*(t25).*3.0e+4).*7.80691184864823e-5-t48.*(t42-t10.*(t16).*3.0e+4).*7.80691184864823e-5+t10.*(t15).*2.342073554594469+t10.*(t27).*2.342073554594469;
    et6 = t10.*t32.*wz.*(t28-t9.*(t25).*3.0e+4).*4.21182894234572e-4+t10.*t49.*wz.*(t41-t9.*(t16).*3.0e+4).*2.950603569539279e-4;
    et7 = t9.*(-1.31628878670393e+1)+t9.*t31.*5.411643582673754+t9.*t48.*3.017608199068512-t9.*t32.*(t28-t9.*(t25).*3.0e+4).*5.577042431427871e-4;
    et8 = t9.*t49.*(t41-t9.*(t16).*3.0e+4).*(-1.873222095424919e-4);
    et9 = t31.*(t29-t10.*(t25).*3.0e+4).*(-1.033742804713229e-4)-t48.*(t42-t10.*(t16).*3.0e+4).*4.956301118488085e-5-t10.*(t15).*1.699303240624486-t10.*(t27).*2.880318992858504;
    et10 = t10.*t32.*wz.*(t28-t9.*(t25).*3.0e+4).*5.577042431427871e-4+t10.*t49.*wz.*(t41-t9.*(t16).*3.0e+4).*1.873222095424919e-4;
    mt5 = [0.0,t145,0.0,0.0,0.0,0.0,1.0,-4.520949326695016e+1,0.0,0.0,0.0,0.0,0.0,t198,t192];
    if ~all(cellfun(@isscalar,{t2,t3}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (t2)    t0 = -t85-t99+4.57962223348299e+1;elseif (t3)    t0 = t85+t99-4.57962223348299e+1;else    t0 = t9.*4.57962223348299-t9.*t31.*3.101228414139687-t9.*t48.*1.486890335546425;end;mt6 = [t0,wz,0.0];
    if ~all(cellfun(@isscalar,{t2,t3}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (t2)    t0 = t190;elseif (t3)    t0 = t191;else    t0 = t89+t121+t136+t141-t9.*t32.*(t28-t9.*t25.*3.0e+4).*1.852199592826479e-3-t9.*t49.*(t41-t9.*t16.*3.0e+4).*1.297561416881591e-3;end;mt7 = [0.0,t0];
    if ~all(cellfun(@isscalar,{t2,t3}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (t2)    t0 = t187;elseif (t3)    t0 = t188;else    t0 = t8+t74+t107+t131-t9.*t32.*(t28-t9.*t25.*3.0e+4).*4.21182894234572e-4-t9.*t49.*(t41-t9.*t16.*3.0e+4).*2.950603569539279e-4;end;mt8 = [t0];
    if ~all(cellfun(@isscalar,{t2,t3}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (t2)    t0 = t86+t113+t126+t147-1.31628878670393e+2;elseif (t3)    t0 = -t86-t113-t126-t147+1.31628878670393e+2;else    t0 = et7+et8;end;if ~all(cellfun(@isscalar,{t3}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (t3)    t1 = t137;else    t1 = et3+et4;end;if ~all(cellfun(@isscalar,{t3}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (t3)    t4 = t11;else    t4 = et5+et6;end;if ~all(cellfun(@isscalar,{t3}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (t3)    t5 = 0.0;else    t5 = et9+et10;end;mt9 = [t0,vy,0.0,0.0,t1,t4,t5,0.0,0.0,0.0,1.808379730678007e+2,0.0,0.0,0.0,0.0];
    J_x_num = reshape([mt5,mt6,mt7,mt8,mt9],6,6);
end
if nargout > 2
    et11 = t71+t65+t58+t72+(-4.397613526523994).*t6+t31.*(t28-t9.*(t25).*3.0e+4).*3.43317811459959e-4+t48.*(t41-t9.*(t16).*3.0e+4).*3.43317811459959e-4;
    et12 = t9.*(t15).*(-1.029953434379877e+1)-t9.*(t27).*1.029953434379877e+1;
    if ~all(cellfun(@isscalar,{t2,t3}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (t2)    t0 = t185;elseif (t3)    t0 = t184;else    t0 = t13-t9.*t15.*2.342073554594469-t9.*t27.*2.342073554594469+t31.*(t28-t9.*t25.*3.0e+4).*7.80691184864823e-5+t48.*(t41-t9.*t16.*3.0e+4).*7.80691184864823e-5;end;mt10 = [phi;t0;wx];
    if ~all(cellfun(@isscalar,{t2,t3}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (t2)    t0 = t6.*(-4.397613526523994)+t58+t65+t71+t72+t77+t78+t135+t153;elseif (t3)    t0 = t6.*(-4.397613526523994)+t58+t65+t71+t72+t76+t80+t132+t150;else    t0 = et11+et12;end;mt11 = [t0;wz;vx];
    h_num = [mt10;mt11];
end
if nargout > 3
    et13 = t11-t31.*(t29-t10.*(t25).*3.0e+4).*7.80691184864823e-5-t48.*(t42-t10.*(t16).*3.0e+4).*7.80691184864823e-5+t10.*(t15).*2.342073554594469+t10.*(t27).*2.342073554594469;
    et14 = t10.*t32.*wz.*(t28-t9.*(t25).*3.0e+4).*4.21182894234572e-4+t10.*t49.*wz.*(t41-t9.*(t16).*3.0e+4).*2.950603569539279e-4;
    et15 = t137-t31.*(t29-t10.*(t25).*3.0e+4).*3.43317811459959e-4-t48.*(t42-t10.*(t16).*3.0e+4).*3.43317811459959e-4+t10.*(t15).*1.029953434379877e+1+t10.*(t27).*1.029953434379877e+1;
    et16 = t10.*t32.*wz.*(t28-t9.*(t25).*3.0e+4).*1.852199592826479e-3+t10.*t49.*wz.*(t41-t9.*(t16).*3.0e+4).*1.297561416881591e-3;
    if ~all(cellfun(@isscalar,{t2,t3}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (t2)    t0 = t187;elseif (t3)    t0 = t188;else    t0 = t8+t74+t107+t131-t9.*t32.*(t28-t9.*t25.*3.0e+4).*4.21182894234572e-4-t9.*t49.*(t41-t9.*t16.*3.0e+4).*2.950603569539279e-4;end;mt12 = [1.0,0.0,0.0,t145,0.0,0.0,0.0,0.0,1.0,-4.520949326695016e+1,0.0,0.0,0.0,t192,0.0,t198,0.0,0.0,0.0,t0,0.0];
    if ~all(cellfun(@isscalar,{t2,t3}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (t2)    t0 = t190;elseif (t3)    t0 = t191;else    t0 = t89+t121+t136+t141-t9.*t32.*(t28-t9.*t25.*3.0e+4).*1.852199592826479e-3-t9.*t49.*(t41-t9.*t16.*3.0e+4).*1.297561416881591e-3;end;if ~all(cellfun(@isscalar,{t3}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (t3)    t1 = t11;else    t1 = et13+et14;end;if ~all(cellfun(@isscalar,{t3}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (t3)    t4 = t137;else    t4 = et15+et16;end;mt13 = [t0,1.0,0.0,0.0,t1,0.0,t4,0.0,1.0,0.0,0.0,0.0];
    mt14 = [1.808379730678007e+2,0.0,0.0];
    J_h_num = reshape([mt12,mt13,mt14],6,6);
end
end
