function [dot_x_num,J_x_num,h_num,J_h_num] = vehicle_dynamics_numeric(in1,Fx,Mz)
%VEHICLE_DYNAMICS_NUMERIC
%    [DOT_X_NUM,J_x_num,H_NUM,J_h_num] = VEHICLE_DYNAMICS_NUMERIC(IN1,Fx,Mz)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    10-Jul-2026 14:10:26

phi = in1(1,:);
phi_u = in1(6,:);
vx = in1(5,:);
vy = in1(3,:);
wx = in1(2,:);
wz = in1(4,:);
t2 = ((vx < 1.0./1.0e+1) & (0.0 <= vx));
t3 = ((-1.0./1.0e+1 < vx) & (vx < 1.0./1.0e+1));
t4 = cos(phi);
t5 = sin(phi);
t6 = vx.*wz;
t7 = wz.*2.0;
t8 = -vx;
t9 = 1.0./vx;
t11 = -wz;
t14 = wz.*(7.0./4.0);
t17 = vy.*3.5e+5;
t18 = wz.*(7.3e+1./2.0e+1);
t19 = wz.*(3.39e+2./1.0e+2);
t20 = wz.*5.395e+1;
t21 = wz.*6.1075e+5;
t33 = wz.*3.779475965327029e+1;
t36 = wz.*7.103165878644602e+5;
t53 = Mz.*2.832172067707477e-5;
t60 = wz.*1.535670251154585e+2;
t61 = vy.*5.342892605730155e+1;
t62 = vy.*5.464838294053761e+1;
t63 = wz.*1.472773920247489e+2;
t64 = phi.*1.808379730678007e+2;
t65 = phi_u.*1.808379730678007e+2;
t66 = wx.*4.520949326695016e+1;
t76 = vy.*2.403224680219713e+2;
t78 = wz.*6.476690513192126e+2;
t131 = vx.*4.397613526523994;
t132 = wz.*4.397613526523994;
t10 = t9.^2;
t12 = -t7;
t13 = -t6;
t16 = t14+vy;
t22 = cos(t20);
t23 = sin(t20);
t24 = t18+vy;
t25 = -t19;
t26 = -t21;
t28 = t9.*wz.*1.88825e+5;
t30 = t9.*wz.*5.395;
t34 = cos(t33);
t35 = sin(t33);
t39 = -t36;
t43 = t9.*wz.*3.779475965327029;
t44 = t9.*wz.*1.32281658786446e+5;
t54 = t4.*2.840464562345316e+1;
t55 = t5.*2.840464562345316e+1;
t67 = -t62;
t68 = -t63;
t69 = -t64;
t70 = -t66;
t71 = t9.*5.464838294053761;
t72 = t9.*1.472773920247489e+1;
t77 = -t76;
t79 = t9.*2.403224680219713e+1;
t82 = -t78;
t91 = t9.*6.476690513192126e+1;
t135 = -t131;
t136 = -t132;
t15 = t12+vy;
t27 = t25+vy;
t29 = t10.*wz.*1.88825e+5;
t31 = cos(t30);
t32 = sin(t30);
t42 = t17+t26;
t45 = t10.*wz.*1.32281658786446e+5;
t48 = cos(t43);
t49 = sin(t43);
t52 = t17+t39;
t56 = -t54;
t57 = -t55;
t75 = -t71;
t83 = -t79;
t85 = t22.*3.618099816496302e+1;
t86 = t22.*6.313584179786047e+1;
t87 = t22.*2.732419147026881e+1;
t88 = t22.*4.768071411561907e+1;
t97 = t22.*1.201612340109856e+2;
t99 = t34.*1.73470539147083e+1;
t100 = t34.*2.732419147026881e+1;
t103 = t22.*2.096813533491699e+2;
t111 = t34.*1.201612340109856e+2;
t112 = t34.*5.545378986090436e+1;
t113 = t34.*3.520542898913264e+1;
t123 = t34.*2.438643363893321e+2;
t89 = -t88;
t90 = -t87;
t101 = -t97;
t102 = -t100;
t104 = t9.*t31.*2.732419147026881;
t105 = t9.*t31.*4.768071411561907;
t106 = -t103;
t114 = t22.*t42.*7.80691184864823e-5;
t115 = -t111;
t116 = -t112;
t118 = t9.*t31.*1.201612340109856e+1;
t119 = t9.*t48.*2.732419147026881;
t122 = t22.*t42.*1.033742804713229e-4;
t124 = t23.*t42.*5.577042431427871e-3;
t125 = t9.*t31.*2.096813533491699e+1;
t126 = t23.*t42.*4.21182894234572e-3;
t127 = -t123;
t129 = t9.*t48.*1.201612340109856e+1;
t130 = t9.*t48.*5.545378986090436;
t134 = t22.*t42.*3.43317811459959e-4;
t140 = t9.*t48.*2.438643363893321e+1;
t141 = t23.*t42.*1.852199592826479e-2;
t142 = t56-1.808379730678007e+2;
t144 = t34.*t52.*7.80691184864823e-5;
t145 = t34.*t52.*4.956301118488085e-5;
t150 = t35.*t52.*1.873222095424919e-3;
t151 = t34.*t52.*3.43317811459959e-4;
t152 = t35.*t52.*2.950603569539279e-3;
t161 = t35.*t52.*1.297561416881591e-2;
t178 = t87+t100+5.464838294053761e+1;
t180 = t97+t111+2.403224680219713e+2;
t107 = -t104;
t117 = -t114;
t120 = -t118;
t121 = -t119;
t128 = -t126;
t133 = -t129;
t138 = -t134;
t143 = -t141;
t146 = -t144;
t153 = -t151;
et1 = t69+t65+t57+t70+(-4.397613526523994).*t6+t31.*(t28-t9.*(t24).*3.5e+4).*3.43317811459959e-4+t48.*(t44-t9.*(t16).*3.5e+4).*3.43317811459959e-4;
et2 = t9.*(t15).*(-1.201612340109856e+1)-t9.*(t27).*1.201612340109856e+1;
if ~all(cellfun(@isscalar,{t2,t3}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (t2)
    t0 = t6.*(-4.397613526523994)+t57+t65+t69+t70+t77+t78+t138+t153;
elseif (t3)
    t0 = t6.*(-4.397613526523994)+t57+t65+t69+t70+t76+t82+t134+t151;
else
    t0 = et1+et2;
end
mt1 = [wx;t0];
if ~all(cellfun(@isscalar,{t2,t3}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (t2)
    t0 = t13+t63+t67+t117+t146;
elseif (t3)
    t0 = t13+t62+t68+t114+t144;
else
    t0 = t13-t9.*t15.*2.732419147026881-t9.*t27.*2.732419147026881+t31.*(t28-t9.*t24.*3.5e+4).*7.80691184864823e-5+t48.*(t44-t9.*t16.*3.5e+4).*7.80691184864823e-5;
end
mt2 = [t0];
if ~all(cellfun(@isscalar,{t2,t3}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (t2)
    t0 = t53-t60+t61-t122-t145;
elseif (t3)
    t0 = t53+t60-t61+t122+t145;
else
    t0 = t53+t9.*t15.*1.982520447395234+t9.*t27.*3.360372158334921+t31.*(t28-t9.*t24.*3.5e+4).*1.033742804713229e-4+t48.*(t44-t9.*t16.*3.5e+4).*4.956301118488085e-5;
end
mt3 = [t0];
mt4 = [Fx.*7.80691184864823e-5+vy.*wz;0.0];
dot_x_num = [mt1;mt2;mt3;mt4];
if nargout > 1
    t154 = -t152;
    t162 = -t161;
    t179 = t90+t102-5.464838294053761e+1;
    t181 = t101+t115-2.403224680219713e+2;
    t184 = t103+t123+t135+t141+t161+6.476690513192126e+2;
    t182 = t75+t107+t121;
    t183 = t83+t120+t133;
    t185 = t106+t127+t135+t143+t162-6.476690513192126e+2;
    if ~all(cellfun(@isscalar,{t2,t3}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (t2)    t186 = t179;elseif (t3)    t186 = t178;else    t186 = t182;end;
    if ~all(cellfun(@isscalar,{t2,t3}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (t2)    t190 = t181;elseif (t3)    t190 = t180;else    t190 = t183;end;
    et3 = t136-t31.*(t29-t10.*(t24).*3.5e+4).*3.43317811459959e-4-t48.*(t45-t10.*(t16).*3.5e+4).*3.43317811459959e-4+t10.*(t15).*1.201612340109856e+1+t10.*(t27).*1.201612340109856e+1;
    et4 = t10.*t32.*wz.*(t28-t9.*(t24).*3.5e+4).*1.852199592826479e-3+t10.*t49.*wz.*(t44-t9.*(t16).*3.5e+4).*1.297561416881591e-3;
    et5 = t11-t31.*(t29-t10.*(t24).*3.5e+4).*7.80691184864823e-5-t48.*(t45-t10.*(t16).*3.5e+4).*7.80691184864823e-5+t10.*(t15).*2.732419147026881+t10.*(t27).*2.732419147026881;
    et6 = t10.*t32.*wz.*(t28-t9.*(t24).*3.5e+4).*4.21182894234572e-4+t10.*t49.*wz.*(t44-t9.*(t16).*3.5e+4).*2.950603569539279e-4;
    et7 = t9.*(-1.535670251154585e+1)+t9.*t31.*6.313584179786047+t9.*t48.*3.520542898913264-t9.*t32.*(t28-t9.*(t24).*3.5e+4).*5.577042431427871e-4;
    et8 = t9.*t49.*(t44-t9.*(t16).*3.5e+4).*(-1.873222095424919e-4);
    et9 = t31.*(t29-t10.*(t24).*3.5e+4).*(-1.033742804713229e-4)-t48.*(t45-t10.*(t16).*3.5e+4).*4.956301118488085e-5-t10.*(t15).*1.982520447395234-t10.*(t27).*3.360372158334921;
    et10 = t10.*t32.*wz.*(t28-t9.*(t24).*3.5e+4).*5.577042431427871e-4+t10.*t49.*wz.*(t44-t9.*(t16).*3.5e+4).*1.873222095424919e-4;
    mt5 = [0.0,t142,0.0,0.0,0.0,0.0,1.0,-4.520949326695016e+1,0.0,0.0,0.0,0.0,0.0,t190,t186];
    if ~all(cellfun(@isscalar,{t2,t3}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (t2)    t0 = -t85-t99+5.342892605730155e+1;elseif (t3)    t0 = t85+t99-5.342892605730155e+1;else    t0 = t9.*5.342892605730155-t9.*t31.*3.618099816496302-t9.*t48.*1.73470539147083;end;mt6 = [t0];
    if ~all(cellfun(@isscalar,{t2,t3}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (t2)    t0 = t184;elseif (t3)    t0 = t185;else    t0 = t91+t125+t135+t140-t9.*t32.*(t28-t9.*t24.*3.5e+4).*1.852199592826479e-3-t9.*t49.*(t44-t9.*t16.*3.5e+4).*1.297561416881591e-3;end;mt7 = [wz,0.0,0.0,t0];
    if ~all(cellfun(@isscalar,{t2,t3}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (t2)    t0 = t8+t88+t112+t126+t152+1.472773920247489e+2;elseif (t3)    t0 = t8+t89+t116+t128+t154-1.472773920247489e+2;else    t0 = t8+t72+t105+t130-t9.*t32.*(t28-t9.*t24.*3.5e+4).*4.21182894234572e-4-t9.*t49.*(t44-t9.*t16.*3.5e+4).*2.950603569539279e-4;end;mt8 = [t0];
    if ~all(cellfun(@isscalar,{t2,t3}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (t2)    t0 = t86+t113+t124+t150-1.535670251154585e+2;elseif (t3)    t0 = -t86-t113-t124-t150+1.535670251154585e+2;else    t0 = et7+et8;end;if ~all(cellfun(@isscalar,{t3}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (t3)    t1 = t136;else    t1 = et3+et4;end;if ~all(cellfun(@isscalar,{t3}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (t3)    t4 = t11;else    t4 = et5+et6;end;if ~all(cellfun(@isscalar,{t3}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (t3)    t5 = 0.0;else    t5 = et9+et10;end;mt9 = [t0,vy,0.0,0.0,t1,t4,t5,0.0,0.0,0.0,1.808379730678007e+2,0.0,0.0,0.0,0.0];
    J_x_num = reshape([mt5,mt6,mt7,mt8,mt9],6,6);
end
if nargout > 2
    et11 = t69+t65+t57+t70+(-4.397613526523994).*t6+t31.*(t28-t9.*(t24).*3.5e+4).*3.43317811459959e-4+t48.*(t44-t9.*(t16).*3.5e+4).*3.43317811459959e-4;
    et12 = t9.*(t15).*(-1.201612340109856e+1)-t9.*(t27).*1.201612340109856e+1;
    if ~all(cellfun(@isscalar,{t2,t3}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (t2)    t0 = t63+t67+t117+t146;elseif (t3)    t0 = t62+t68+t114+t144;else    t0 = t9.*t15.*(-2.732419147026881)-t9.*t27.*2.732419147026881+t31.*(t28-t9.*t24.*3.5e+4).*7.80691184864823e-5+t48.*(t44-t9.*t16.*3.5e+4).*7.80691184864823e-5;end;mt10 = [phi;t0;wx];
    if ~all(cellfun(@isscalar,{t2,t3}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (t2)    t0 = t6.*(-4.397613526523994)+t57+t65+t69+t70+t77+t78+t138+t153;elseif (t3)    t0 = t6.*(-4.397613526523994)+t57+t65+t69+t70+t76+t82+t134+t151;else    t0 = et11+et12;end;mt11 = [t0;wz;vx];
    h_num = [mt10;mt11];
end
if nargout > 3
    et13 = t31.*(t29-t10.*(t24).*3.5e+4).*(-7.80691184864823e-5)-t48.*(t45-t10.*(t16).*3.5e+4).*7.80691184864823e-5+t10.*(t15).*2.732419147026881+t10.*(t27).*2.732419147026881;
    et14 = t10.*t32.*wz.*(t28-t9.*(t24).*3.5e+4).*4.21182894234572e-4+t10.*t49.*wz.*(t44-t9.*(t16).*3.5e+4).*2.950603569539279e-4;
    et15 = t136-t31.*(t29-t10.*(t24).*3.5e+4).*3.43317811459959e-4-t48.*(t45-t10.*(t16).*3.5e+4).*3.43317811459959e-4+t10.*(t15).*1.201612340109856e+1+t10.*(t27).*1.201612340109856e+1;
    et16 = t10.*t32.*wz.*(t28-t9.*(t24).*3.5e+4).*1.852199592826479e-3+t10.*t49.*wz.*(t44-t9.*(t16).*3.5e+4).*1.297561416881591e-3;
    mt12 = [1.0,0.0,0.0,t142,0.0,0.0,0.0,0.0,1.0,-4.520949326695016e+1,0.0,0.0,0.0,t186,0.0,t190,0.0,0.0,0.0];
    if ~all(cellfun(@isscalar,{t2,t3}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (t2)    t0 = t88+t112+t126+t152+1.472773920247489e+2;elseif (t3)    t0 = t89+t116+t128+t154-1.472773920247489e+2;else    t0 = t72+t105+t130-t9.*t32.*(t28-t9.*t24.*3.5e+4).*4.21182894234572e-4-t9.*t49.*(t44-t9.*t16.*3.5e+4).*2.950603569539279e-4;end;mt13 = [t0,0.0];
    if ~all(cellfun(@isscalar,{t2,t3}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (t2)    t0 = t184;elseif (t3)    t0 = t185;else    t0 = t91+t125+t135+t140-t9.*t32.*(t28-t9.*t24.*3.5e+4).*1.852199592826479e-3-t9.*t49.*(t44-t9.*t16.*3.5e+4).*1.297561416881591e-3;end;if ~all(cellfun(@isscalar,{t3}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (t3)    t1 = 0.0;else    t1 = et13+et14;end;if ~all(cellfun(@isscalar,{t3}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (t3)    t4 = t136;else    t4 = et15+et16;end;mt14 = [t0,1.0,0.0,0.0,t1,0.0,t4,0.0,1.0,0.0,0.0,0.0];
    mt15 = [1.808379730678007e+2,0.0,0.0];
    J_h_num = reshape([mt12,mt13,mt14,mt15],6,6);
end
end
