- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

- ros_topic_name: "ouster/points"
  gz_topic_name: "/ouster/scan/points"
  #ros_type_name: "sensor_msgs/msg/LaserScan"
  #gz_type_name: "gz.msgs.LaserScan"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS 

- ros_topic_name: "/osdome1/scan"
  gz_topic_name: "/osdome1/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS
  frame_id: "osdome_link1_1"

- ros_topic_name: "osdome2/scan"
  gz_topic_name: "/osdome2/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS 

- ros_topic_name: "osdome3/scan"
  gz_topic_name: "/osdome3/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS 