function [dot_x_num,J_x_num,h_num,J_h_num] = vehicle_dynamics_real(in1,Fx,Mz)
%VEHICLE_DYNAMICS_REAL
%    [DOT_X_NUM,J_x_num,H_NUM,J_h_num] = VEHICLE_DYNAMICS_REAL(IN1,Fx,Mz)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    14-Jul-2026 17:48:34

phi = in1(1,:);
phi_u = in1(6,:);
vx = in1(5,:);
vy = in1(3,:);
wx = in1(2,:);
wz = in1(4,:);
t2 = ((vx < 3.0./2.0) & (0.0 <= vx));
t3 = ((-3.0./2.0 < vx) & (vx < 3.0./2.0));
t4 = vx.*wz;
t5 = wz.*2.0;
t6 = -phi_u;
t7 = -vx;
t8 = 1.0./vx;
t10 = -wz;
t13 = wz.*(7.0./4.0);
t19 = wz.*(7.3e+1./2.0e+1);
t20 = wz.*(3.39e+2./1.0e+2);
t22 = vy.*2.333333333333333e+4;
t24 = wz.*3.596666666666667;
t25 = wz.*4.071666666666667e+4;
t35 = wz.*2.519650643551353;
t36 = wz.*4.735443919096401e+4;
t55 = Mz.*2.832172067707477e-5;
t58 = vy.*3.561928403820104;
t59 = wz.*1.02378016743639e+1;
t60 = phi.*1.808379730678007e+2;
t61 = phi_u.*1.808379730678007e+2;
t62 = wx.*4.520949326695016e+1;
t63 = vy.*3.643225529369174;
t67 = wz.*9.818492801649924;
t74 = vy.*1.602149786813142e+1;
t79 = wz.*4.317793675461417e+1;
t126 = vx.*4.397613526523994;
t127 = wz.*4.397613526523994;
t9 = t8.^2;
t11 = -t5;
t12 = -t4;
t14 = phi+t6;
t18 = t13+vy;
t21 = t19+vy;
t23 = -t20;
t26 = cos(t24);
t27 = sin(t24);
t28 = -t25;
t30 = t8.*wz.*1.88825e+5;
t32 = t8.*wz.*5.395;
t37 = cos(t35);
t38 = sin(t35);
t39 = -t36;
t44 = t8.*wz.*3.779475965327029;
t45 = t8.*wz.*1.32281658786446e+5;
t64 = -t60;
t65 = -t62;
t66 = -t63;
t68 = t8.*5.464838294053761;
t69 = t8.*1.472773920247489e+1;
t72 = -t67;
t75 = -t74;
t76 = t8.*2.403224680219713e+1;
t82 = -t79;
t87 = t8.*6.476690513192126e+1;
t130 = -t126;
t132 = -t127;
t15 = t11+vy;
t16 = cos(t14);
t17 = sin(t14);
t29 = t23+vy;
t31 = t9.*wz.*1.88825e+5;
t33 = cos(t32);
t34 = sin(t32);
t46 = t9.*wz.*1.32281658786446e+5;
t49 = cos(t44);
t50 = sin(t44);
t53 = t22+t28;
t54 = t22+t39;
t73 = -t68;
t80 = -t76;
t83 = t26.*2.412066544330868;
t84 = t26.*4.209056119857364;
t85 = t26.*1.821612764684587;
t86 = t26.*3.178714274374604;
t94 = t26.*8.010748934065709;
t98 = t37.*1.156470260980553;
t99 = t37.*1.821612764684587;
t100 = t26.*1.397875688994466e+1;
t108 = t37.*8.010748934065709;
t111 = t37.*3.696919324060291;
t112 = t37.*2.347028599275509;
t121 = t37.*1.625762242595547e+1;
t88 = -t86;
t89 = -t85;
t97 = -t94;
t101 = t8.*t33.*2.732419147026881;
t102 = t8.*t33.*4.768071411561907;
t103 = -t99;
t104 = -t100;
t110 = -t108;
t113 = t8.*t33.*1.201612340109856e+1;
t114 = -t111;
t115 = t8.*t49.*2.732419147026881;
t118 = t8.*t33.*2.096813533491699e+1;
t119 = t26.*t53.*7.80691184864823e-5;
t122 = -t121;
t123 = t26.*t53.*1.033742804713229e-4;
t124 = t8.*t49.*1.201612340109856e+1;
t125 = t8.*t49.*5.545378986090436;
t129 = t27.*t53.*3.718028287618581e-4;
t131 = t17.*4.314058869520038e+1;
t133 = t27.*t53.*2.807885961563814e-4;
t135 = t16.*4.314058869520038e+1;
t140 = t8.*t49.*2.438643363893321e+1;
t141 = t26.*t53.*3.43317811459959e-4;
t143 = t37.*t54.*7.80691184864823e-5;
t144 = t37.*t54.*4.956301118488085e-5;
t146 = t27.*t53.*1.234799728550986e-3;
t151 = t37.*t54.*3.43317811459959e-4;
t152 = t38.*t54.*1.248814730283279e-4;
t154 = t38.*t54.*1.967069046359519e-4;
t165 = t38.*t54.*8.650409445877276e-4;
t181 = t85+t99+3.643225529369174;
t183 = t94+t108+1.602149786813142e+1;
t105 = -t101;
t116 = -t113;
t117 = -t115;
t120 = -t119;
t128 = -t124;
t136 = -t131;
t137 = -t133;
t139 = -t135;
t142 = -t141;
t145 = -t143;
t147 = -t146;
t153 = -t151;
et1 = t64+t61+t136+t65+(-4.397613526523994).*t4+t33.*(t30-t8.*(t21).*3.5e+4).*3.43317811459959e-4+t49.*(t45-t8.*(t18).*3.5e+4).*3.43317811459959e-4;
et2 = t8.*(t15).*(-1.201612340109856e+1)-t8.*(t29).*1.201612340109856e+1;
if ~all(cellfun(@isscalar,{t2,t3}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (t2)
    t0 = t4.*(-4.397613526523994)+t61+t64+t65+t75+t79+t136+t142+t153;
elseif (t3)
    t0 = t4.*(-4.397613526523994)+t61+t64+t65+t74+t82+t136+t141+t151;
else
    t0 = et1+et2;
end
mt1 = [wx;t0];
if ~all(cellfun(@isscalar,{t2,t3}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (t2)
    t0 = t12+t66+t67+t120+t145;
elseif (t3)
    t0 = t12+t63+t72+t119+t143;
else
    t0 = t12-t8.*t15.*2.732419147026881-t8.*t29.*2.732419147026881+t33.*(t30-t8.*t21.*3.5e+4).*7.80691184864823e-5+t49.*(t45-t8.*t18.*3.5e+4).*7.80691184864823e-5;
end
mt2 = [t0];
if ~all(cellfun(@isscalar,{t2,t3}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (t2)
    t0 = t55+t58-t59-t123-t144;
elseif (t3)
    t0 = t55-t58+t59+t123+t144;
else
    t0 = t55+t8.*t15.*1.982520447395234+t8.*t29.*3.360372158334921+t33.*(t30-t8.*t21.*3.5e+4).*1.033742804713229e-4+t49.*(t45-t8.*t18.*3.5e+4).*4.956301118488085e-5;
end
mt3 = [t0];
mt4 = [Fx.*7.80691184864823e-5+vy.*wz;0.0];
dot_x_num = [mt1;mt2;mt3;mt4];
if nargout > 1
    t155 = -t154;
    t166 = -t165;
    t174 = t135+1.808379730678007e+2;
    t182 = t89+t103-3.643225529369174;
    t184 = t97+t110-1.602149786813142e+1;
    t187 = t100+t121+t130+t146+t165+4.317793675461417e+1;
    t177 = t139-1.808379730678007e+2;
    t185 = t73+t105+t117;
    t186 = t80+t116+t128;
    t188 = t104+t122+t130+t147+t166-4.317793675461417e+1;
    if ~all(cellfun(@isscalar,{t2,t3}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (t2)    t189 = t182;elseif (t3)    t189 = t181;else    t189 = t185;end;
    if ~all(cellfun(@isscalar,{t2,t3}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (t2)    t191 = t184;elseif (t3)    t191 = t183;else    t191 = t186;end;
    et3 = t132-t33.*(t31-t9.*(t21).*3.5e+4).*3.43317811459959e-4-t49.*(t46-t9.*(t18).*3.5e+4).*3.43317811459959e-4+t9.*(t15).*1.201612340109856e+1+t9.*(t29).*1.201612340109856e+1;
    et4 = t9.*t34.*wz.*(t30-t8.*(t21).*3.5e+4).*1.852199592826479e-3+t9.*t50.*wz.*(t45-t8.*(t18).*3.5e+4).*1.297561416881591e-3;
    et5 = t10-t33.*(t31-t9.*(t21).*3.5e+4).*7.80691184864823e-5-t49.*(t46-t9.*(t18).*3.5e+4).*7.80691184864823e-5+t9.*(t15).*2.732419147026881+t9.*(t29).*2.732419147026881;
    et6 = t9.*t34.*wz.*(t30-t8.*(t21).*3.5e+4).*4.21182894234572e-4+t9.*t50.*wz.*(t45-t8.*(t18).*3.5e+4).*2.950603569539279e-4;
    et7 = t8.*(-1.535670251154585e+1)+t8.*t33.*6.313584179786047+t8.*t49.*3.520542898913264-t8.*t34.*(t30-t8.*(t21).*3.5e+4).*5.577042431427871e-4;
    et8 = t8.*t50.*(t45-t8.*(t18).*3.5e+4).*(-1.873222095424919e-4);
    et9 = t33.*(t31-t9.*(t21).*3.5e+4).*(-1.033742804713229e-4)-t49.*(t46-t9.*(t18).*3.5e+4).*4.956301118488085e-5-t9.*(t15).*1.982520447395234-t9.*(t29).*3.360372158334921;
    et10 = t9.*t34.*wz.*(t30-t8.*(t21).*3.5e+4).*5.577042431427871e-4+t9.*t50.*wz.*(t45-t8.*(t18).*3.5e+4).*1.873222095424919e-4;
    mt5 = [0.0,t177,0.0,0.0,0.0,0.0,1.0,-4.520949326695016e+1,0.0,0.0,0.0,0.0,0.0,t191,t189];
    if ~all(cellfun(@isscalar,{t2,t3}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (t2)    t0 = -t83-t98+3.561928403820104;elseif (t3)    t0 = t83+t98-3.561928403820104;else    t0 = t8.*5.342892605730155-t8.*t33.*3.618099816496302-t8.*t49.*1.73470539147083;end;mt6 = [t0];
    if ~all(cellfun(@isscalar,{t2,t3}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (t2)    t0 = t187;elseif (t3)    t0 = t188;else    t0 = t87+t118+t130+t140-t8.*t34.*(t30-t8.*t21.*3.5e+4).*1.852199592826479e-3-t8.*t50.*(t45-t8.*t18.*3.5e+4).*1.297561416881591e-3;end;mt7 = [wz,0.0,0.0,t0];
    if ~all(cellfun(@isscalar,{t2,t3}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (t2)    t0 = t7+t86+t111+t133+t154+9.818492801649924;elseif (t3)    t0 = t7+t88+t114+t137+t155-9.818492801649924;else    t0 = t7+t69+t102+t125-t8.*t34.*(t30-t8.*t21.*3.5e+4).*4.21182894234572e-4-t8.*t50.*(t45-t8.*t18.*3.5e+4).*2.950603569539279e-4;end;mt8 = [t0];
    if ~all(cellfun(@isscalar,{t2,t3}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (t2)    t0 = t84+t112+t129+t152-1.02378016743639e+1;elseif (t3)    t0 = -t84-t112-t129-t152+1.02378016743639e+1;else    t0 = et7+et8;end;if ~all(cellfun(@isscalar,{t3}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (t3)    t1 = t132;else    t1 = et3+et4;end;if ~all(cellfun(@isscalar,{t3}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (t3)    t4 = t10;else    t4 = et5+et6;end;if ~all(cellfun(@isscalar,{t3}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (t3)    t5 = 0.0;else    t5 = et9+et10;end;mt9 = [t0,vy,0.0,0.0,t1,t4,t5,0.0,0.0,0.0,t174,0.0,0.0,0.0,0.0];
    J_x_num = reshape([mt5,mt6,mt7,mt8,mt9],6,6);
end
if nargout > 2
    et11 = t64+t61+t136+t65+(-4.397613526523994).*t4+t33.*(t30-t8.*(t21).*3.5e+4).*3.43317811459959e-4+t49.*(t45-t8.*(t18).*3.5e+4).*3.43317811459959e-4;
    et12 = t8.*(t15).*(-1.201612340109856e+1)-t8.*(t29).*1.201612340109856e+1;
    if ~all(cellfun(@isscalar,{t2,t3}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (t2)    t0 = t66+t67+t120+t145;elseif (t3)    t0 = t63+t72+t119+t143;else    t0 = t8.*t15.*(-2.732419147026881)-t8.*t29.*2.732419147026881+t33.*(t30-t8.*t21.*3.5e+4).*7.80691184864823e-5+t49.*(t45-t8.*t18.*3.5e+4).*7.80691184864823e-5;end;mt10 = [phi;t0;wx];
    if ~all(cellfun(@isscalar,{t2,t3}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (t2)    t0 = t4.*(-4.397613526523994)+t61+t64+t65+t75+t79+t136+t142+t153;elseif (t3)    t0 = t4.*(-4.397613526523994)+t61+t64+t65+t74+t82+t136+t141+t151;else    t0 = et11+et12;end;mt11 = [t0;wz;vx];
    h_num = [mt10;mt11];
end
if nargout > 3
    et13 = t33.*(t31-t9.*(t21).*3.5e+4).*(-7.80691184864823e-5)-t49.*(t46-t9.*(t18).*3.5e+4).*7.80691184864823e-5+t9.*(t15).*2.732419147026881+t9.*(t29).*2.732419147026881;
    et14 = t9.*t34.*wz.*(t30-t8.*(t21).*3.5e+4).*4.21182894234572e-4+t9.*t50.*wz.*(t45-t8.*(t18).*3.5e+4).*2.950603569539279e-4;
    et15 = t132-t33.*(t31-t9.*(t21).*3.5e+4).*3.43317811459959e-4-t49.*(t46-t9.*(t18).*3.5e+4).*3.43317811459959e-4+t9.*(t15).*1.201612340109856e+1+t9.*(t29).*1.201612340109856e+1;
    et16 = t9.*t34.*wz.*(t30-t8.*(t21).*3.5e+4).*1.852199592826479e-3+t9.*t50.*wz.*(t45-t8.*(t18).*3.5e+4).*1.297561416881591e-3;
    mt12 = [1.0,0.0,0.0,t177,0.0,0.0,0.0,0.0,1.0,-4.520949326695016e+1,0.0,0.0,0.0,t189,0.0,t191,0.0,0.0,0.0];
    if ~all(cellfun(@isscalar,{t2,t3}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (t2)    t0 = t86+t111+t133+t154+9.818492801649924;elseif (t3)    t0 = t88+t114+t137+t155-9.818492801649924;else    t0 = t69+t102+t125-t8.*t34.*(t30-t8.*t21.*3.5e+4).*4.21182894234572e-4-t8.*t50.*(t45-t8.*t18.*3.5e+4).*2.950603569539279e-4;end;mt13 = [t0];
    if ~all(cellfun(@isscalar,{t2,t3}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (t2)    t0 = t187;elseif (t3)    t0 = t188;else    t0 = t87+t118+t130+t140-t8.*t34.*(t30-t8.*t21.*3.5e+4).*1.852199592826479e-3-t8.*t50.*(t45-t8.*t18.*3.5e+4).*1.297561416881591e-3;end;if ~all(cellfun(@isscalar,{t3}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (t3)    t1 = 0.0;else    t1 = et13+et14;end;if ~all(cellfun(@isscalar,{t3}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (t3)    t4 = t132;else    t4 = et15+et16;end;mt14 = [0.0,t0,1.0,0.0,0.0,t1,0.0,t4,0.0,1.0,0.0,0.0,0.0,t174,0.0,0.0];
    J_h_num = reshape([mt12,mt13,mt14],6,6);
end
end
