function [dot_x_num,J_x_num,h_num,J_h_num] = vehicle_dynamics_real(in1,Fx,Mz)
%VEHICLE_DYNAMICS_REAL
%    [DOT_X_NUM,J_x_num,H_NUM,J_h_num] = VEHICLE_DYNAMICS_REAL(IN1,Fx,Mz)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    10-Jul-2026 17:18:46

phi = in1(1,:);
phi_u = in1(6,:);
vx = in1(5,:);
vy = in1(3,:);
wx = in1(2,:);
wz = in1(4,:);
t2 = ((vx < 3.0./2.0) & (0.0 <= vx));
t3 = ((-3.0./2.0 < vx) & (vx < 3.0./2.0));
t4 = cos(phi);
t5 = sin(phi);
t6 = vx.*wz;
t7 = wz.*2.0;
t8 = -vx;
t9 = 1.0./vx;
t11 = -wz;
t14 = wz.*(7.0./4.0);
t17 = wz.*(7.3e+1./2.0e+1);
t18 = wz.*(3.39e+2./1.0e+2);
t20 = vy.*2.333333333333333e+4;
t22 = wz.*3.596666666666667;
t23 = wz.*4.071666666666667e+4;
t33 = wz.*2.519650643551353;
t34 = wz.*4.735443919096401e+4;
t53 = Mz.*2.832172067707477e-5;
t60 = vy.*3.561928403820104;
t61 = wz.*1.02378016743639e+1;
t62 = phi.*1.808379730678007e+2;
t63 = phi_u.*1.808379730678007e+2;
t64 = wx.*4.520949326695016e+1;
t65 = vy.*3.643225529369174;
t69 = wz.*9.818492801649924;
t76 = vy.*1.602149786813142e+1;
t81 = wz.*4.317793675461417e+1;
t128 = vx.*4.397613526523994;
t129 = wz.*4.397613526523994;
t10 = t9.^2;
t12 = -t7;
t13 = -t6;
t16 = t14+vy;
t19 = t17+vy;
t21 = -t18;
t24 = cos(t22);
t25 = sin(t22);
t26 = -t23;
t28 = t9.*wz.*1.88825e+5;
t30 = t9.*wz.*5.395;
t35 = cos(t33);
t36 = sin(t33);
t37 = -t34;
t42 = t9.*wz.*3.779475965327029;
t43 = t9.*wz.*1.32281658786446e+5;
t54 = t4.*2.840464562345316e+1;
t55 = t5.*2.840464562345316e+1;
t66 = -t62;
t67 = -t64;
t68 = -t65;
t70 = t9.*5.464838294053761;
t71 = t9.*1.472773920247489e+1;
t74 = -t69;
t77 = -t76;
t78 = t9.*2.403224680219713e+1;
t84 = -t81;
t89 = t9.*6.476690513192126e+1;
t132 = -t128;
t133 = -t129;
t15 = t12+vy;
t27 = t21+vy;
t29 = t10.*wz.*1.88825e+5;
t31 = cos(t30);
t32 = sin(t30);
t44 = t10.*wz.*1.32281658786446e+5;
t47 = cos(t42);
t48 = sin(t42);
t51 = t20+t26;
t52 = t20+t37;
t56 = -t54;
t57 = -t55;
t75 = -t70;
t82 = -t78;
t85 = t24.*2.412066544330868;
t86 = t24.*4.209056119857364;
t87 = t24.*1.821612764684587;
t88 = t24.*3.178714274374604;
t96 = t24.*8.010748934065709;
t100 = t35.*1.156470260980553;
t101 = t35.*1.821612764684587;
t102 = t24.*1.397875688994466e+1;
t110 = t35.*8.010748934065709;
t113 = t35.*3.696919324060291;
t114 = t35.*2.347028599275509;
t123 = t35.*1.625762242595547e+1;
t90 = -t88;
t91 = -t87;
t99 = -t96;
t103 = t9.*t31.*2.732419147026881;
t104 = t9.*t31.*4.768071411561907;
t105 = -t101;
t106 = -t102;
t112 = -t110;
t115 = t9.*t31.*1.201612340109856e+1;
t116 = -t113;
t117 = t9.*t47.*2.732419147026881;
t120 = t9.*t31.*2.096813533491699e+1;
t121 = t24.*t51.*7.80691184864823e-5;
t124 = -t123;
t125 = t24.*t51.*1.033742804713229e-4;
t126 = t9.*t47.*1.201612340109856e+1;
t127 = t9.*t47.*5.545378986090436;
t131 = t25.*t51.*3.718028287618581e-4;
t134 = t25.*t51.*2.807885961563814e-4;
t138 = t9.*t47.*2.438643363893321e+1;
t139 = t24.*t51.*3.43317811459959e-4;
t140 = t56-1.808379730678007e+2;
t142 = t35.*t52.*7.80691184864823e-5;
t143 = t35.*t52.*4.956301118488085e-5;
t145 = t25.*t51.*1.234799728550986e-3;
t150 = t35.*t52.*3.43317811459959e-4;
t151 = t36.*t52.*1.248814730283279e-4;
t153 = t36.*t52.*1.967069046359519e-4;
t164 = t36.*t52.*8.650409445877276e-4;
t178 = t87+t101+3.643225529369174;
t180 = t96+t110+1.602149786813142e+1;
t107 = -t103;
t118 = -t115;
t119 = -t117;
t122 = -t121;
t130 = -t126;
t136 = -t134;
t141 = -t139;
t144 = -t142;
t146 = -t145;
t152 = -t150;
et1 = t66+t63+t57+t67+(-4.397613526523994).*t6+t31.*(t28-t9.*(t19).*3.5e+4).*3.43317811459959e-4+t47.*(t43-t9.*(t16).*3.5e+4).*3.43317811459959e-4;
et2 = t9.*(t15).*(-1.201612340109856e+1)-t9.*(t27).*1.201612340109856e+1;
if ~all(cellfun(@isscalar,{t2,t3}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (t2)
    t0 = t6.*(-4.397613526523994)+t57+t63+t66+t67+t77+t81+t141+t152;
elseif (t3)
    t0 = t6.*(-4.397613526523994)+t57+t63+t66+t67+t76+t84+t139+t150;
else
    t0 = et1+et2;
end
mt1 = [wx;t0];
if ~all(cellfun(@isscalar,{t2,t3}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (t2)
    t0 = t13+t68+t69+t122+t144;
elseif (t3)
    t0 = t13+t65+t74+t121+t142;
else
    t0 = t13-t9.*t15.*2.732419147026881-t9.*t27.*2.732419147026881+t31.*(t28-t9.*t19.*3.5e+4).*7.80691184864823e-5+t47.*(t43-t9.*t16.*3.5e+4).*7.80691184864823e-5;
end
mt2 = [t0];
if ~all(cellfun(@isscalar,{t2,t3}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (t2)
    t0 = t53+t60-t61-t125-t143;
elseif (t3)
    t0 = t53-t60+t61+t125+t143;
else
    t0 = t53+t9.*t15.*1.982520447395234+t9.*t27.*3.360372158334921+t31.*(t28-t9.*t19.*3.5e+4).*1.033742804713229e-4+t47.*(t43-t9.*t16.*3.5e+4).*4.956301118488085e-5;
end
mt3 = [t0];
mt4 = [Fx.*7.80691184864823e-5+vy.*wz;0.0];
dot_x_num = [mt1;mt2;mt3;mt4];
if nargout > 1
    t154 = -t153;
    t165 = -t164;
    t179 = t91+t105-3.643225529369174;
    t181 = t99+t112-1.602149786813142e+1;
    t184 = t102+t123+t132+t145+t164+4.317793675461417e+1;
    t182 = t75+t107+t119;
    t183 = t82+t118+t130;
    t185 = t106+t124+t132+t146+t165-4.317793675461417e+1;
    if ~all(cellfun(@isscalar,{t2,t3}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (t2)    t186 = t179;elseif (t3)    t186 = t178;else    t186 = t182;end;
    if ~all(cellfun(@isscalar,{t2,t3}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (t2)    t190 = t181;elseif (t3)    t190 = t180;else    t190 = t183;end;
    et3 = t133-t31.*(t29-t10.*(t19).*3.5e+4).*3.43317811459959e-4-t47.*(t44-t10.*(t16).*3.5e+4).*3.43317811459959e-4+t10.*(t15).*1.201612340109856e+1+t10.*(t27).*1.201612340109856e+1;
    et4 = t10.*t32.*wz.*(t28-t9.*(t19).*3.5e+4).*1.852199592826479e-3+t10.*t48.*wz.*(t43-t9.*(t16).*3.5e+4).*1.297561416881591e-3;
    et5 = t11-t31.*(t29-t10.*(t19).*3.5e+4).*7.80691184864823e-5-t47.*(t44-t10.*(t16).*3.5e+4).*7.80691184864823e-5+t10.*(t15).*2.732419147026881+t10.*(t27).*2.732419147026881;
    et6 = t10.*t32.*wz.*(t28-t9.*(t19).*3.5e+4).*4.21182894234572e-4+t10.*t48.*wz.*(t43-t9.*(t16).*3.5e+4).*2.950603569539279e-4;
    et7 = t9.*(-1.535670251154585e+1)+t9.*t31.*6.313584179786047+t9.*t47.*3.520542898913264-t9.*t32.*(t28-t9.*(t19).*3.5e+4).*5.577042431427871e-4;
    et8 = t9.*t48.*(t43-t9.*(t16).*3.5e+4).*(-1.873222095424919e-4);
    et9 = t31.*(t29-t10.*(t19).*3.5e+4).*(-1.033742804713229e-4)-t47.*(t44-t10.*(t16).*3.5e+4).*4.956301118488085e-5-t10.*(t15).*1.982520447395234-t10.*(t27).*3.360372158334921;
    et10 = t10.*t32.*wz.*(t28-t9.*(t19).*3.5e+4).*5.577042431427871e-4+t10.*t48.*wz.*(t43-t9.*(t16).*3.5e+4).*1.873222095424919e-4;
    mt5 = [0.0,t140,0.0,0.0,0.0,0.0,1.0,-4.520949326695016e+1,0.0,0.0,0.0,0.0,0.0,t190,t186];
    if ~all(cellfun(@isscalar,{t2,t3}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (t2)    t0 = -t85-t100+3.561928403820104;elseif (t3)    t0 = t85+t100-3.561928403820104;else    t0 = t9.*5.342892605730155-t9.*t31.*3.618099816496302-t9.*t47.*1.73470539147083;end;mt6 = [t0];
    if ~all(cellfun(@isscalar,{t2,t3}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (t2)    t0 = t184;elseif (t3)    t0 = t185;else    t0 = t89+t120+t132+t138-t9.*t32.*(t28-t9.*t19.*3.5e+4).*1.852199592826479e-3-t9.*t48.*(t43-t9.*t16.*3.5e+4).*1.297561416881591e-3;end;mt7 = [wz,0.0,0.0,t0];
    if ~all(cellfun(@isscalar,{t2,t3}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (t2)    t0 = t8+t88+t113+t134+t153+9.818492801649924;elseif (t3)    t0 = t8+t90+t116+t136+t154-9.818492801649924;else    t0 = t8+t71+t104+t127-t9.*t32.*(t28-t9.*t19.*3.5e+4).*4.21182894234572e-4-t9.*t48.*(t43-t9.*t16.*3.5e+4).*2.950603569539279e-4;end;mt8 = [t0];
    if ~all(cellfun(@isscalar,{t2,t3}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (t2)    t0 = t86+t114+t131+t151-1.02378016743639e+1;elseif (t3)    t0 = -t86-t114-t131-t151+1.02378016743639e+1;else    t0 = et7+et8;end;if ~all(cellfun(@isscalar,{t3}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (t3)    t1 = t133;else    t1 = et3+et4;end;if ~all(cellfun(@isscalar,{t3}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (t3)    t4 = t11;else    t4 = et5+et6;end;if ~all(cellfun(@isscalar,{t3}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (t3)    t5 = 0.0;else    t5 = et9+et10;end;mt9 = [t0,vy,0.0,0.0,t1,t4,t5,0.0,0.0,0.0,1.808379730678007e+2,0.0,0.0,0.0,0.0];
    J_x_num = reshape([mt5,mt6,mt7,mt8,mt9],6,6);
end
if nargout > 2
    et11 = t66+t63+t57+t67+(-4.397613526523994).*t6+t31.*(t28-t9.*(t19).*3.5e+4).*3.43317811459959e-4+t47.*(t43-t9.*(t16).*3.5e+4).*3.43317811459959e-4;
    et12 = t9.*(t15).*(-1.201612340109856e+1)-t9.*(t27).*1.201612340109856e+1;
    if ~all(cellfun(@isscalar,{t2,t3}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (t2)    t0 = t68+t69+t122+t144;elseif (t3)    t0 = t65+t74+t121+t142;else    t0 = t9.*t15.*(-2.732419147026881)-t9.*t27.*2.732419147026881+t31.*(t28-t9.*t19.*3.5e+4).*7.80691184864823e-5+t47.*(t43-t9.*t16.*3.5e+4).*7.80691184864823e-5;end;mt10 = [phi;t0;wx];
    if ~all(cellfun(@isscalar,{t2,t3}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (t2)    t0 = t6.*(-4.397613526523994)+t57+t63+t66+t67+t77+t81+t141+t152;elseif (t3)    t0 = t6.*(-4.397613526523994)+t57+t63+t66+t67+t76+t84+t139+t150;else    t0 = et11+et12;end;mt11 = [t0;wz;vx];
    h_num = [mt10;mt11];
end
if nargout > 3
    et13 = t31.*(t29-t10.*(t19).*3.5e+4).*(-7.80691184864823e-5)-t47.*(t44-t10.*(t16).*3.5e+4).*7.80691184864823e-5+t10.*(t15).*2.732419147026881+t10.*(t27).*2.732419147026881;
    et14 = t10.*t32.*wz.*(t28-t9.*(t19).*3.5e+4).*4.21182894234572e-4+t10.*t48.*wz.*(t43-t9.*(t16).*3.5e+4).*2.950603569539279e-4;
    et15 = t133-t31.*(t29-t10.*(t19).*3.5e+4).*3.43317811459959e-4-t47.*(t44-t10.*(t16).*3.5e+4).*3.43317811459959e-4+t10.*(t15).*1.201612340109856e+1+t10.*(t27).*1.201612340109856e+1;
    et16 = t10.*t32.*wz.*(t28-t9.*(t19).*3.5e+4).*1.852199592826479e-3+t10.*t48.*wz.*(t43-t9.*(t16).*3.5e+4).*1.297561416881591e-3;
    mt12 = [1.0,0.0,0.0,t140,0.0,0.0,0.0,0.0,1.0,-4.520949326695016e+1,0.0,0.0,0.0,t186,0.0,t190,0.0,0.0,0.0];
    if ~all(cellfun(@isscalar,{t2,t3}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (t2)    t0 = t88+t113+t134+t153+9.818492801649924;elseif (t3)    t0 = t90+t116+t136+t154-9.818492801649924;else    t0 = t71+t104+t127-t9.*t32.*(t28-t9.*t19.*3.5e+4).*4.21182894234572e-4-t9.*t48.*(t43-t9.*t16.*3.5e+4).*2.950603569539279e-4;end;mt13 = [t0];
    if ~all(cellfun(@isscalar,{t2,t3}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (t2)    t0 = t184;elseif (t3)    t0 = t185;else    t0 = t89+t120+t132+t138-t9.*t32.*(t28-t9.*t19.*3.5e+4).*1.852199592826479e-3-t9.*t48.*(t43-t9.*t16.*3.5e+4).*1.297561416881591e-3;end;if ~all(cellfun(@isscalar,{t3}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (t3)    t1 = 0.0;else    t1 = et13+et14;end;if ~all(cellfun(@isscalar,{t3}))    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));end;if (t3)    t4 = t133;else    t4 = et15+et16;end;mt14 = [0.0,t0,1.0,0.0,0.0,t1,0.0,t4,0.0,1.0,0.0,0.0,0.0];
    mt15 = [1.808379730678007e+2,0.0,0.0];
    J_h_num = reshape([mt12,mt13,mt14,mt15],6,6);
end
end
